# Generated by Django 5.1.2 on 2025-02-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
    ]
