# Generated by Django 5.1.2 on 2025-04-10 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomamenity',
            old_name='name',
            new_name='amenity_name',
        ),
        migrations.AlterField(
            model_name='resident',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resident',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(help_text='Upload image of the room', upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(help_text='Maximum capacity of the room'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='facilities',
            field=models.TextField(blank=True, help_text='General facilities description'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='floor',
            field=models.CharField(help_text='Floor number or location', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='maintenance',
            field=models.TextField(blank=True, help_text='Maintenance notes'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rental price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, help_text='Security deposit amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='size',
            field=models.CharField(help_text='Size of the room (e.g., 10x10 sq ft)', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='total_rooms',
            field=models.IntegerField(help_text='Total number of rooms available'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(help_text='Name of the room type (e.g., Single Room)', max_length=100, unique=True),
        ),
    ]
